### ISSUE TITLE
Preview button not functioning in DatoCMS

### ISSUE THREAD

**Issue by jacobcarrington** [gatsby-inc/datocms-plugin-gatsby-cloud#11]
Hi there, 

I seem to be having some issues getting preview to work. I’ve setup Gatsby Cloud and run through the automated integration with Dato. Builds seem to trigger correctly, the generated preview updates with live data very quickly. All things appear to be working correctly apart from the CMS preview button plugin (https://github.com/gatsby-inc/datocms-plugin-gatsby-cloud 2) which doesn’t respond. There are errors in the console being generate on click: 

![Error screenshot](https://community.datocms.com/uploads/default/original/1X/2201a98d077ae5b3da15fdb72f6ba16151604898.png)

I have a slug field present on all models that relate to pages. I’m using chrome canary: Version 82.0.4084.0 (Official Build) canary (64-bit)

I'll continue to look into this myself but it looks to be coming out if the ExtensionUI module from '@gatsby-cloud-pkg/gatsby-cms-extension-base'.

Any help would be appreciated

**Comment by jacobcarrington** [comment]
Looks like it might have something to do with multi language support. Will confirm shortly

**Comment by jacobcarrington** [comment]
So I've confirmed this is an issue with Multi language. In the cause of multilang, the field value is an object, not a string, hence the error here.

**Comment by jacobcarrington** [comment]
I'm not sure how common my situation is where I have: 
1. One Git Repo
2. One DatoCMS repo with 2 Languages
3. Two sites on difference domains, where the language is dictated by the .env file. 

In order to preview my both languages, I require 2 instances of Gatsby preview. This in-of-itself meant that I required to mirrored repo's in github (i use gitlab for my origin) as both would require different env configurations. 

This then means, I'll require either a preview plugin pre language ( Which i don't think is possible). 
Or a configuration that allows for multiple preview links. On a positive note, in terms of keeping backwards compatibility, it seems that the API key remains constant for both preview instances which would mean we only need to allow for a field to add multiple preview links. 

In addition, another is listening for the change in language, and updating the state with the correct language. This is what I'm currently working on. Progress is somewhat tedious as local tunnelling no longer works for me.

**Comment by floristenhove** [comment]
We're also experiencing this same issue when using multiple languages within DatoCMS. We'll try to create a PR when we have time to fix this.

**Comment by jacobcarrington** [comment]
I've created a working version here: https://github.com/e2digital/datocms-plugin-gatsby-cloud

The only way I could get this to work was by creating multiple buttons.

**Comment by jacobcarrington** [comment]
The languageConfig option follows this shape: 
`[
  {
    "languange": "en-AU",
    "instanceUrl": "",
    "authToken": ""
  },
]`

**Comment by stefanoverna** [comment]
This should fix the issue!

**Comment by jacobcarrington** [comment]
> This should fix the issue! ⬆️

Legend!

**Comment by stefanoverna** [comment]
Published as datocms-plugin-gatsby-cloud  @ 0.1.7

**Comment by DSchau** [comment]
Thanks @stefanoverna! Closing!
